# Generated by Django 5.2 on 2025-04-05 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("birthday_sync", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="googleevent",
            name="contact",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="birthday_sync.googlecontact",
            ),
        ),
    ]
