# Generated by Django 5.2 on 2025-04-05 12:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("birthday_sync", "0003_alter_googleevent_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="googlecontact",
            name="google_event_id",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name="GoogleEvent",
        ),
    ]
