# Generated by Django 5.2 on 2025-04-08 16:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("birthday_sync", "0004_googlecontact_google_event_id_delete_googleevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="googlecontact",
            name="is_updated",
            field=models.BooleanField(default=False),
        ),
    ]
